image: snakemake/snakemake

tasks:
  - name: main terminal
    command: |
      rm Dockerfile
      echo "PS1='\w\$ '" >> ~/.bashrc
      conda init
      source ~/.bashrc
      clear
      
vscode:
  extensions:
    - snakemake.snakemake-lang
    - ms-toolsai.jupyter
    - sndst00m.vscode-native-svg-preview
