channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal >=7.3
  - jinja2
  - matplotlib
  - graphviz
  - bcftools =1.15
  - samtools =1.15
  - bwa =0.7.17
  - pysam =0.19
  - pygments
  - fastqc =0.11.9
  - trimmomatic =0.39
  - picard =2.27.5
  - freebayes=1.3.6
